---
version: "v4"
defaultSpecies: "hsapiens"
logLevel: "info"
logFile: ""

## These are the RESTful configurations parameters
rest:
  hosts:
  - "bioinfodev.hpc.cam.ac.uk/cellbase"
  - "bioinfodev.hpc.cam.ac.uk/cellbase-4.5.0-rc2.1"
  timeout: 2000
grpc:
  host: "localhost:9091"
